FROM rust:1.73-bookworm as builder
WORKDIR /usr/src/app

COPY api ./api
COPY cli ./cli
COPY src ./src
COPY Cargo.lock ./Cargo.lock
COPY Cargo.toml ./Cargo.toml
RUN cargo install --path ./api

FROM debian:bookworm-slim
COPY --from=builder /usr/local/cargo/bin/api /usr/local/bin/api
RUN apt-get update && apt-get install -y pkg-config libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*
RUN update-ca-certificates

ENV HOST=0.0.0.0
ENV PORT=8080

CMD api --host $HOST --port  $PORT