name: Build and Publish

on:
  push:
    branches: [master]
  pull_request:
  
jobs:
  build-and-push-image:
    name: Build Docker image and push to registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          
      - name: Build and Push to Registry
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.api
          tags: ${{github.actor}}/proxy-downloader:latest
          push: ${{ github.ref == 'refs/heads/master' }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
